spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2/database/chuk-check
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  expire:
    access: 1
    refresh: 12
  security:
    key: NOp+vt6xPFIfG3ZWlp8N7a6B8nB/94fh7rByuugmVFE=